name: diffusion_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15
  - pip=24.0
  - numpy=1.26.4
  - pandas=2.2.2
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - diffusers=0.31.0
  - transformers=4.41.0
  - accelerate=0.30.1
  - datasets=2.19.1
  - safetensors=0.4.3
  - scipy=1.13.0
  - tqdm=4.66.4
  - pip:
      - -r requirements.txt
      - aiohttp==3.10.5
      - beautifulsoup4==4.12.2
      - filelock==3.14.0
      - huggingface-hub==0.26.2
      - matplotlib==3.9.0
      - networkx==3.3
      - pillow==10.3.0
      - regex==2024.5.15
      - sympy==1.12
      - tokenizers==0.19.1
      - triton==2.3.0
      - fsspec==2024.5.0
      - git-lfs==1.6
      - pyparsing==3.1.2
      - zipp==3.18.2
      # NVIDIA CUDA dependencies (Ensure GPU support)
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
