eta_values: [1.0, 1.17, 1.34, 1.51, 1.68, 1.85]
variance_scales: [1.00, 1.02, 1.03, 1.04]
score_type: "CLIP"
base_images_path: "/share/u/kevin/DiffusionConceptErasure/new_probe_code/results/base_model/"
mask_size: [256, 256]
