eta_values: [1.0, 1.17, 1.34, 1.51, 1.68, 1.85]
variance_scales: [1.00, 1.02, 1.03, 1.04]
mask_size: [256, 256]
classifier_scales: [25, 32, 39, 46, 53, 60, 67, 74, 81, 88, 95, 102, 109, 116, 123, 130, 137, 144, 151, 158, 165, 172, 179, 186, 193]
num_inference_steps: 50
guidance_scale: 7.5
